/** Stable local paths under /public — no remote/temporary URLs. */
export const assets = {
  projectCoat: "/home/first-card.png",
  projectPhones: "/home/second-card.png",
  projectMitte: "/work/Portada Mitte.png",
  projectUciPhoto: "/work/uci/PortadaUCI.png",
  uciHeroVideo: "/work/uci/UciPortada.mp4",
  uciSketchBack: "/work/uci/Sketch/Sketch1.png",
  uciSketchFront:
    "/work/uci/Sketch/Captura de pantalla 2024-01-10 a las 15.33 5.png",
  uciTimeline: "/work/uci/Timeline.png?v=3",
  uciStartingPoint: "/work/uci/StartingPoint.png?v=2",
  uciMetrics1: "/work/uci/Metrics1.png",
  uciMetrics2: "/work/uci/Metrics%202.png",
  uciArchitecture: "/work/uci/Architecture.png?v=2",
  uciContentTipology: "/work/uci/ContentTipology.png",
  uciUsageEndesa: "/work/uci/UsagePatterns/Endesa.png",
  uciUsageSantander: "/work/uci/UsagePatterns/Santande.png",
  uciUsageMafre: "/work/uci/UsagePatterns/Mafre.png",
  uciEndesaBuscador: "/work/uci/EndesaBuscador.png",
  uciPodcast: "/work/uci/Podcast.png",
  uciArticleRepsol: "/work/uci/ArticlePatterns/RepsolArticle.png?v=2",
  uciArticleEndesa: "/work/uci/ArticlePatterns/EndesaArticle.png?v=2",
  uciArticleSantander: "/work/uci/ArticlePatterns/SantanderArticle.png?v=2",
  uciHomepageV02: "/work/uci/Homepage_v.02.png",
  uciActualidadV02: "/work/uci/Actualidad_v.02.png",
  uciDetalleNotaPrensa: "/work/uci/DetalleNotaPrensa.png",
  uciCrossSellingActualidad: "/work/uci/CrossSelling/ActualidadNoticias.png",
  uciCrossSellingDetalle: "/work/uci/CrossSelling/DetalleNotaPrensa_v.01.png",
  uciDesignSystem: "/work/uci/UCIDesignSystem.png",
  uciNavMegamenu01: "/work/uci/Navigation/Megamenu_01.png",
  uciNavMegamenu02: "/work/uci/Navigation/Megamenu_02.png",
  uciNavAnchorMenus01: "/work/uci/Navigation/AnchorMenus_01.png",
  uciNavAnchorMenus02: "/work/uci/Navigation/AnchorMenus_02.png",
  uciNavAnchorMenus03: "/work/uci/Navigation/AnchorMenus_03.png",
  zoneOldDesign: "/work/zone/ZoneOldDesign.png",
  zoneMoodboard: "/work/zone/Moodboard.png?v=2",
  zoneWalkthrough: "/work/zone/AppCbreWalkthrough.webm?v=2",
  zoneWalkthroughSource: "/work/zone/AppCbreWalkthrough.mp4",
  zoneNews: "/work/zone/NewsZone.webm",
  zoneNewsSource: "/work/zone/NewsZone.mp4",
  zoneCalendar: "/work/zone/CalendarZone.webm",
  zoneCalendarSource: "/work/zone/CalendarZone.mp4",
  zoneWorkspace: "/work/zone/WorkspaceZone.webm",
  zoneWorkspaceSource: "/work/zone/WorkspaceZone.mp4",
  zoneDashboard: "/work/zone/DashboardZone.webm",
  zoneDashboardSource: "/work/zone/DashboardsZOne.mp4",
  zoneFavourite: "/work/zone/FavouriteZone.webm?v=2",
  zoneFavouriteSource: "/work/zone/FavouriteZone.mp4?v=2",
  aboutPortrait: "/about/portrait.png",
  dsBrandsSample: "/work/ds-brands/DS_Sample.png",
  dsBrandsTypography: "/work/ds-brands/Typography.png",
  dsBrandsComponents: "/work/ds-brands/Components.png",
  menuIcon: "/icons/IconMenu.svg",
} as const;
