/** Stable local paths under /public — raster images are WebP. */
export const assets = {
  projectCoat: "/home/first-card.webp",
  projectPhones: "/home/second-card.webp",
  projectMitte: "/work/Portada Mitte.webp",
  projectUciPhoto: "/work/uci/PortadaUCI.webp",
  uciHeroVideo: "/work/uci/UciPortada.mp4",
  uciSketchBack: "/work/uci/Sketch/Sketch1.webp",
  uciSketchFront:
    "/work/uci/Sketch/Captura de pantalla 2024-01-10 a las 15.33 5.webp",
  uciTimeline: "/work/uci/Timeline.webp",
  uciStartingPoint: "/work/uci/StartingPoint.webp",
  uciMetrics1: "/work/uci/Metrics1.webp",
  uciMetrics2: "/work/uci/Metrics%202.webp",
  uciArchitecture: "/work/uci/Architecture.webp",
  uciContentTipology: "/work/uci/ContentTipology.webp",
  uciUsageEndesa: "/work/uci/UsagePatterns/Endesa.webp",
  uciUsageSantander: "/work/uci/UsagePatterns/Santande.webp",
  uciUsageMafre: "/work/uci/UsagePatterns/Mafre.webp",
  uciEndesaBuscador: "/work/uci/EndesaBuscador.webp",
  uciPodcast: "/work/uci/Podcast.webp",
  uciArticleRepsol: "/work/uci/ArticlePatterns/RepsolArticle.webp",
  uciArticleEndesa: "/work/uci/ArticlePatterns/EndesaArticle.webp",
  uciArticleSantander: "/work/uci/ArticlePatterns/SantanderArticle.webp",
  uciHomepageV02: "/work/uci/Homepage_v.02.webp",
  uciActualidadV02: "/work/uci/Actualidad_v.02.webp",
  uciDetalleNotaPrensa: "/work/uci/DetalleNotaPrensa.webp",
  uciCrossSellingActualidad: "/work/uci/CrossSelling/ActualidadNoticias.webp",
  uciCrossSellingDetalle: "/work/uci/CrossSelling/DetalleNotaPrensa_v.01.webp",
  uciDesignSystem: "/work/uci/UCIDesignSystem.webp",
  uciNavMegamenu01: "/work/uci/Navigation/Megamenu_01.webp",
  uciNavMegamenu02: "/work/uci/Navigation/Megamenu_02.webp",
  uciNavAnchorMenus01: "/work/uci/Navigation/AnchorMenus_01.webp",
  uciNavAnchorMenus02: "/work/uci/Navigation/AnchorMenus_02.webp",
  uciNavAnchorMenus03: "/work/uci/Navigation/AnchorMenus_03.webp",
  zoneOldDesign: "/work/zone/ZoneOldDesign.webp",
  zoneMoodboard: "/work/zone/Moodboard.webp",
  zoneWalkthrough: "/work/zone/AppCbreWalkthrough.webm?v=2",
  zoneWalkthroughSource: "/work/zone/AppCbreWalkthrough.mp4",
  zoneNews: "/work/zone/NewsZone.webm",
  zoneNewsSource: "/work/zone/NewsZone.mp4",
  zoneCalendar: "/work/zone/CalendarZone.webm",
  zoneCalendarSource: "/work/zone/CalendarZone.mp4",
  zoneWorkspace: "/work/zone/WorkspaceZone.webm",
  zoneWorkspaceSource: "/work/zone/WorkspaceZone.mp4",
  zoneDashboard: "/work/zone/DashboardZone.webm",
  zoneDashboardSource: "/work/zone/DashboardsZOne.mp4",
  zoneFavourite: "/work/zone/FavouriteZone.webm?v=2",
  zoneFavouriteSource: "/work/zone/FavouriteZone.mp4?v=2",
  aboutPortrait: "/about/portrait.webp",
  dsBrandsSample: "/work/ds-brands/DS_Sample.webp",
  dsBrandsTypography: "/work/ds-brands/Typography.webp",
  dsBrandsComponents: "/work/ds-brands/Components.webp",
  menuIcon: "/icons/IconMenu.svg",
} as const;
